name: Trivy Security Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: '24 20 * * 5'

permissions:
  contents: read

jobs:
  trivy-scan:
    permissions:
      contents: read
      security-events: write
      actions: read
    name: Trivy Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image '${{ vars.DOCKER_REPOSITORY }}:${{ github.sha }}'
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          push: false
          tags: |
            ${{ vars.DOCKER_REPOSITORY }}:${{ github.sha }}

      - name: Run Trivy vulnerability scanner (SARIF)
        if: ${{ github.event_name != 'workflow_dispatch' || github.ref == 'refs/heads/main' }}
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{ vars.DOCKER_REPOSITORY }}:${{ github.sha }}"
          format: "sarif"
          output: "trivy-results.sarif"
          exit-code: "0"
          ignore-unfixed: true
          vuln-type: "os,library"
          scanners: "vuln"
          severity: "CRITICAL,HIGH"

      - name: Run Trivy vulnerability scanner (console)
        if: ${{ github.event_name == 'workflow_dispatch' && github.ref != 'refs/heads/main' }}
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{ vars.DOCKER_REPOSITORY }}:${{ github.sha }}"
          format: "table"
          exit-code: "0"
          ignore-unfixed: true
          vuln-type: "os,library"
          scanners: "vuln"
          severity: "CRITICAL,HIGH"

      - name: Upload Trivy scan results to GitHub Security tab
        if: ${{ always() && (github.event_name != 'workflow_dispatch' || github.ref == 'refs/heads/main') }}
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: "trivy-results.sarif"
